version: "3.7"
services:
  reverse-proxy:
    image: traefik:v2.1
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
      - "--metrics.influxdb=true"
      - "--metrics.influxdb.address=influxdb:8086"
      - "--metrics.influxdb.database=traefik"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    # Dynamic Configuration
    labels:
      #- "traefik.http.routers.router0.rule=Host(`traefik.naturbana.org`)"
      #- "traefik.http.routers.router0.service=api@internal"
      #- "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.traefik.entrypoints=websecure"
      #- "traefik.http.routers.traefik.middlewares=auth"
      #- "traefik.http.middlewares.auth.basicauth.users=joan:$$2y$$05$$fRPF2svFNbcoenyCorOaaunoF7nKqu/EawT3uj.VQ47/MyGAnJeGq"
       # Redirect all HTTP to HTTPS permanently
      - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http_catchall.entrypoints=web
      - traefik.http.routers.http_catchall.middlewares=https_redirect
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - "traefik.http.routers.api.rule=Host(`traefik.naturbana.org`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=joan:$$2y$$05$$LJEWyCCFuKVJ/rrDj/H8g.wHsjml8LyM8BjRlo.QHxmpn8qZzJwH6"

      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.entrypoints=websecure"


  influxdb:
    image: influxdb:1.7.9
    ports:
      - '8086:8086'
    volumes:
      - /opt/influxdb/storage:/var/lib/influxdb
    labels:
      - "traefik.http.routers.influxdb.rule=Host(`stats.naturbana.org`)"
    environment:
      - INFLUXDB_DB=naturbana
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    depends_on: [reverse-proxy]

  chronograf:
    image: chronograf:1.7.16
    #ports:
    #  - '8888:8888'
    volumes:
      - /opt/chronograf/storage:/var/lib/chronograf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.naturbana.org`)"
      - "traefik.http.routers.chronograf.entrypoints=websecure"
      - "traefik.http.routers.chronograf.tls.certresolver=letsencrypt"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - TOKEN_SECRET=${CHRONOGRAPH_TOKEN_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PUBLIC_URL=${CHRONOGRAF_PUBLIC_URL}
      - GOOGLE_DOMAINS=${GOOGLE_DOMAINS}
    depends_on: [influxdb]

  grafana:
    image: grafana/grafana:6.6.2
    user: ${GRAFANA_USER_ID}
    #ports:
    #  - '3000:3000'
    volumes:
      - /opt/grafana/storage:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.naturbana.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_INSTALL_PLUGINS=andig-darksky-datasource
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1m
      #- GF_SMTP_ENABLED=true
      #- GF_SMTP_HOST
      #- GF_SMTP_USER
      #- GF_SMTP_PASSWORD
      #- GF_SMTP_FROM_ADDRESS
      #- GF_SMTP_FROM_NAME
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=info
    depends_on: [influxdb]
